### ISSUE TITLE
Compile Error on mysql-chef_gem: could not find recipe default for cookbook mysql-chef_gem

### ISSUE THREAD

**Issue by dasomx77** [opscode-cookbooks/database#101]
It seems as if the mysql-chef_gem cookbook was edited 3 days ago but the database cookbook was not edited to match the new requirements. The Recipe folder in mysql-chef_gem was removed and the database cookbook is including the default recipe in its mysql.rb recipe... Based on what the new readme says on the mysql-chef_gem cookbook, shouldn't the include_recipe statement be removed from the mysql.rb recipe and replaced by the resource that uses the lwrp? (since that resource is now missing from the default recipe of the mysql-chef_gem?)

**Comment by dasomx77** [comment]
same here... Thanks

**Comment by gokulnath** [comment]
https://github.com/opscode-cookbooks/database/issues/99

**Comment by kameshsampath** [comment]
@sandoracs  thanks you solution worked for me as well, it will be great if chef database cookbook owners update this
