### ISSUE TITLE
Update dependency on mysql cookbook to support v6.0+

### ISSUE THREAD

**Issue by ajkerr** [opscode-cookbooks/database#103]
The dependency on the mysql cookbook is defined as:
```
depends 'mysql', '~> 5.0'
```

The mysql cookbook is now at version 6.0.3 - could the dependency be updated to support the latest mysql cookbook versions?

**Comment by lluiscanals** [comment]
The mysql cookbook is now at version 6.0.6
+1

**Comment by ajkerr** [comment]
It looks like version 3.0.3 of this cookbook doesn't have an explicit dependency on the mysql cookbook.  Perhaps this issues can be closed?

**Comment by lluiscanals** [comment]
Yes, It can be closed.

**Comment by ajkerr** [comment]
Closing, the dependency has been removed.
