### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by jenssegers** [opscode-cookbooks/database#104]
Is there an easy way to get this working for MariaDB?

**Comment by kramvan1** [comment]
Looks like effort here would be to mostly cut/paste the existing mysql support and create new mariadb supported db type.

**Comment by bpieck** [comment]
Use in mysql2_chef_gem den mariadb provider

**Comment by someara** [comment]
^ yep. that's the solution. v4.x has been decoupled from the mysql gem. You can use the mysql2_chef_gem resource and the mariadb provider to use the mariadb libs.
