### ISSUE TITLE
Update naming of mysql-chef_gem (dash) to be mysql_chef_gem (underscore)

### ISSUE THREAD

**Issue by mgolfieri** [opscode-cookbooks/database#106]
mysql-chef_gem went under renaming yesterday when going from 1.0.0 to 2.0.0.  This cookbook should reflect it, otherwise converging will fail. In my case:

Chef::Exceptions::RecipeNotFound       
--------------------------------       
could not find recipe default for cookbook mysql-chef_gem       

Locking version of Berksfile doesn't help, as it only controls level 1 inclusions, and can't force 3rd party ones such as the one for the database cookbook.

**Comment by marko-ciric** [comment]
+1

**Comment by someara** [comment]
Fixed... mysql-chef_gem deprecated in favor of mysql_chef_gem.
Also, the database cookbook now uses mysql2_chef_gem
