### ISSUE TITLE
Using mysql_database LWRP requires that node['mysql']['version'] be set

### ISSUE THREAD

**Issue by trappar** [opscode-cookbooks/database#111]
If you try to use the mysql_database LWRP without setting node['mysql']['version'], you get an error converging [here](https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql.rb#L33).

Defining the attribute fixes the problem.

**Comment by drag00n** [comment]
I believe that this is expected. Would you prefer a particular error message or a default value?

**Comment by trappar** [comment]
An error would be nice, but mostly I think this just needs to be documented.

**Comment by arvidbjorkstrom** [comment]
When the mentioned line was fixed in 3.0.3 I got a similar error from [this line](https://github.com/opscode-cookbooks/database/blob/master/recipes/mysql.rb#L3).

For other people who got this error and tried to google the error messages but got no useful hits, I'll post my errors here so others can find this page easier :)

```
==> default: Error executing action `install` on resource 'mysql2_chef_gem[default]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `version' for Chef::Resource::MysqlClient
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
==> default: 
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/database/recipes/mysql.rb
==> default: 
==> default:   2: mysql2_chef_gem 'default' do
==> default:   3:   client_version node['mysql']['version'] if node['mysql']
==> default:   4:   action :install
==> default:   5: end
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/database/recipes/mysql.rb:2:in `from_file'
==> default: 
==> default: mysql2_chef_gem("default") do
==> default:   action [:install]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   declared_type :mysql2_chef_gem
==> default:   cookbook_name :database
==> default:   recipe_name "mysql"
==> default: end
```

**Comment by wubrg** [comment]
Has there been any update on this issue?

**Comment by dnataraj** [comment]
I still have to set node.default['mysql']['version'] = '5.7' in order for 3.0.3 to work.

**Comment by wubrg** [comment]
The error above seems to be a problem with the version of mysql community cookbook being used. We are still on a 5.x flavor but the mysql and mysql2 chef_gems have a dependency on the latest versions of the mysql community coookbook. A change from 5 -> 6 included the removal of the 'version' parameter to the mysql_client resource.

**Comment by phillipsnick** [comment]
I'm having this same problem using the following cookbooks:
database 3.0.3
mysql 5.6.1

**Comment by someara** [comment]
v4.x has been decoupled from the mysql gem. You can use the mysql2_chef_gem resource directly in your recipe before them mysql_database or mysql_database_user resources and select your version directly.

**Comment by junjihashimoto** [comment]
In my environment, mysql2_chef_gem calls mysql_client's version attribute.
But mysql_client does not have the attribute.
This causes above error. So I comment out the function call. See below.

cookbooks version are following.
mysql 5.6.1
database 3.1.0
mysql2_chef_gem 1.0.1

```
-- a/berks-cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb
+++ b/berks-cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb
@@ -14,7 +14,7 @@ class Chef
 
           # As a resource: can pass version from calling recipe
           mysql_client 'default' do
-            #version new_resource.client_version
+            version new_resource.client_version
             action :create
           end
```

**Comment by junjihashimoto** [comment]
In my case,  node.default['mysql']['version'] = '5.7' is not needed.

**Comment by hammi85** [comment]
I also get the "undefined method `version' for Chef::Resource::MysqlClient" error. Are there any updates on that issue? I could really need some help with that.

**Comment by junjihashimoto** [comment]
After above my comment, I tried using 4.x, then the error occurred.

Currently installing mysql2_chef_gem is removed, so I think the error will not occur.
https://github.com/opscode-cookbooks/database/commit/b1941c6bf25d120c941b89b44044ee323baf7c7a
