### ISSUE TITLE
:query action seems to be missing for MySQL

### ISSUE THREAD

**Issue by ajkerr** [opscode-cookbooks/database#118]
Using the latest version (3.0.3) of this cookbook, I'm getting the following error when trying to use the :query action with mysql_database:

==> database: NoMethodError
==> database: -------------
==> database: No resource or method named `action_query' for `Chef::Provider::Database::Mysql ""'

Indeed, looking at the provider_database_mysql.rb file, I see that there is no :query action defined.  Is this an oversight?  This action is still referred to in the README and is also present in the providers for SQL Server and PostgreSQL.

**Comment by chrisferry** [comment]
:+1:

**Comment by jamestoyer** [comment]
:+1:

**Comment by nievo** [comment]
:+1:

**Comment by rbugajewski** [comment]
Yeah, the new database cookbook 3.x is horrible compared to previous versions. The `GRANT OPTION` doesn’t work anymore, the `query` action is missing etc.

This should’ve been much longer in development and not marked as 3.x before most of the functions from previous versions were (re-)implemented & tested.

**Comment by paulczar** [comment]
Yeah, this is breaking me as well.   not only that but the 'pre 3.x no longer works unless you pin the mysql_gem cookbook to `v0.0.5` in Berksfile because it expects to see a default recipe in the mysql_gem cookbook.

**Comment by ajkerr** [comment]
Closing since #119 has been merged.
