### ISSUE TITLE
MariaDB support planned ?

### ISSUE THREAD

**Issue by BarthV** [opscode-cookbooks/database#120]
Hi !

Do you plan to support MariaDB ? It should not be very different from mysql.
Curently this cookbook realize some versions/output checks that blocks mariadb mysql client usage (even when I'm trying to fake real mysql behaviour) :

**Comment by bpieck** [comment]
Hi,
I already use this cookbook with mariadb. In my case mysql_database and so on works with it, too. I just had to set the provider of mysql2_chef_gem to Chef::Provider::Mysql2ChefGem::Mariadb
(I used 

    Chef::Platform.set platform: :ubuntu, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mariadb

before using mysql_database resources to do overwrite https://github.com/sinfomicien/mysql2_chef_gem/blob/master/libraries/z_provider_mapping.rb settings, without wrapping this cookbook - but perhaps there is a better way, to set a default provider without need to set it in mysql2_chef_gem resource itself).

**Comment by BarthV** [comment]
Hey thx for your post :)
I'll try to use mysql2 gem Right now.

If it works (it seems to) maybe it's a good idée to upgrade/backport providers upstream (just an idea) ?

**Comment by bpieck** [comment]
This cookbook already uses mysqh2_chef_gem https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql.rb
My only problem with this was, that mysql2_chef_gem uses per default Mysql Provider. So I really only needed that one line above, to make this cookbook working with mariadb.

**Comment by BarthV** [comment]
Hi !
So i just added in my code (as you said) :
```Chef::Platform.set platform: :ubuntu, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mariadb```

and then I called :
```
mysql_database_user 'john' do
  connection mariadb_conn #it's a simple conf hash :)
  password 'doe'
end
```

But it's not working, ... Does it was really the only thing you changed to make this work :'( ?

**Comment by BarthV** [comment]
just find out why user provider didn't worked (and database one did) :
* #121 
* #110

**Comment by jenssegers** [comment]
@BarthV I'm unable to get it working as well at this moment. Having issues with the client complaining about an unsupported client version.

Does the version check need to be this strict? For example, on debian you have the dotdeb repository, which includes a mysql 5.6 version. In this case it will also complain about an unsupported version as it is set to 5.5.

**Comment by BarthV** [comment]
currently it works if you use this PR branch ( https://github.com/BarthV/database/tree/mysqluser-allow-noversion ) with this code :

```ruby
# It seems to work without this line too ...
Chef::Platform.set platform: :ubuntu, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mariadb

mysql2_chef_gem 'default' do
  provider Chef::Provider::Mysql2ChefGem::Mariadb
  action :install
end

mysql_database_user 'nagios' do
  connection myconn
  host '%'
  privileges    [:super,:process,:select]
  password 'mypassword'
end
```

**Comment by bpieck** [comment]
Yeah, first line is not needed, if you specify provider in mysql2_chef_gem. Your solution is better, than mine, since yours works on all supported plattforms, while I've overwritten it only on ubuntu ^^

**Comment by someara** [comment]
^ yep. that's the solution. v4.x has been decoupled from the mysql gem. You can use the mysql2_chef_gem resource and the mariadb provider to use the mariadb libs.
