### ISSUE TITLE
PostgreSQL 8.4.20 doesn't understand CREATE USER ... NOREPLICATION

### ISSUE THREAD

**Issue by juliandunn** [opscode-cookbooks/database#136]
#125 added support for user privileges to the postgresql_database_user LWRP. Unfortunately this breaks user creation on PostgreSQL 8.4.20 because this version doesn't understand the `NOREPLICATION` syntax.

**Comment by kisoku** [comment]
See #132, which will be merged shortly

**Comment by kisoku** [comment]
Seriously though, no one in their right ming should be using PostgreSQL 8.x at this point. It's both EOL and there have been a ton of vulns fixed since the EOLed the *.x series. 

That being said. We are still going to fix it.

**Comment by kisoku** [comment]
Just released 4.0.3 with a fix for this. Closing

**Comment by juliandunn** [comment]
@kisoku sadly (or perhaps wonderfully, depending on your viewpoint) CentOS 6.x still ships with 8.4.x. But thanks for the fix.
