### ISSUE TITLE
Resources using pssword should honor sensitive flag 

### ISSUE THREAD

**Issue by runwaldarshu** [opscode-cookbooks/database#137]
In database cookbook I found one place where password is being printed in log message which will not be right if consumer is using sensitive flag which is supported by chef from 11.4.2 + versions \[1\].

In entire project there is one place in database_mysql_user LWPR for grant action \[2\] where password is part of sql statement and that is being printed in log.  
All other places like create user, grant in other providers has been avoiding printing password.
I am planning on submitting PR to not log that message. For the consistency sake this seemed fine.
If that's not acceptable I can addd a check for sensitive flag and then log it. 

\[1\]: https://tickets.opscode.com/browse/CHEF-5098
\[2\]: https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql_user.rb#L130

**Comment by evaryont** [comment]
I think this can be closed now? #138 was merged, so this doesn't apply any more.
