### ISSUE TITLE
Is there a way to add superuser to a user?

### ISSUE THREAD

**Issue by luck02** [opscode-cookbooks/database#74]
I'm trying to make one of my users superuser, I'd think there would be a way to specify that in the create user stanza:

postgresql_database_user node['app']['username'] do
connection postgresql_connection_info
password node['app']['password']
privileges [:superuser] <-- like this?
action [ :create, :grant]
end

However, that doesn't work.  Cant find in the documentation.  In the absence of that I'm trying this:

postgresql_database 'makeGooseSuperUser' do
  connection postgresql_connection_info
  sql        'alter role suRole with superuser;'
  action     :query
end

Which doesn't seem to work either.  It's like chef doesn't see that stanza.

**Comment by wzcolon** [comment]
@bkett Thanks.

**Comment by tmaier** [comment]
According to https://github.com/chef-cookbooks/database/blob/b76d55c9bbeeb6b7d684b88f89f5801a29486a47/test/fixtures/cookbooks/postgresql_database_test/recipes/default.rb#L63-L69, you must set `superuser true` on the `postgresql_database_user` LWRP.

https://github.com/chef-cookbooks/database/blob/b76d55c9bbeeb6b7d684b88f89f5801a29486a47/libraries/provider_database_postgresql_user.rb#L48
