### ISSUE TITLE
Database - Mysql - Centos6.5

### ISSUE THREAD

**Issue by kameshsampath** [opscode-cookbooks/database#91]
Hi,

When i run the chef database cook for mysql on cent os 6.5 i get the following error, 

```
==> default: [2014-10-23T18:15:26+05:30] ERROR: mysql_service[default] (mysql::server line 20) had an error: NoMethodError: undefined method `sensitive' for Chef::Resource::Execute
==> default: [2014-10-23T18:15:26+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Where in the same cookbook runs pretty well on Ubuntu Trusty 14.04 

Platform 
-----------
 Chef 11.16.0 
 Vagrant 1.6.5
 Database cookbook v 2.3.0
 Cent OS 6.5

Thanks.

**Comment by someara** [comment]
This should be fixed in 4.x
