### ISSUE TITLE
MySQL install fails on amazon platform

### ISSUE THREAD

**Issue by xaniasd** [opscode-cookbooks/database#96]
Hi,

I'm using cookbooks database (2.3.0) and mysql (5.6.1) to do a basic installation of MySQL 5.6 on an Amazon EC2 instance (AMI 2014.03). I can see in the logs that MySQL 5.5 is installed first (by mysql-chef_gem), which subsequently creates conflicts with the packages of MySQL 5.6. Apart from the obvious inefficiency, this means that support for amazon is not really there.

Am I missing something? Are these cookbooks not supposed to be used together?

Thanks

ps: I'm using Chef 11.16.4

**Comment by someara** [comment]
This is fixed in the current version. The database cookbook now depends on the mysql2_chef_gem, which was explicitly tested on Amazon.
